// Step 1: Import our Hostinger MySQL connection pool
const db = require('../config/db');

class RotationService {
  /**
   * Fetch all academic blocks for a specific residency program
   * @param {number} programId - e.g., 1 for Family Medicine
   */
  static async getBlocksByProgram(programId) {
    // Prepared statement using ? prevents SQL Injection attacks
    const query = `
      SELECT 
        b.id AS block_id,
        b.program_id,
        p.program_code,
        p.week_start_day,
        b.academic_year,
        b.block_number,
        b.block_name,
        b.start_date,
        b.end_date,
        DAYNAME(b.start_date) AS actual_start_day
      FROM rotation_blocks b
      JOIN programs p ON p.id = b.program_id
      WHERE b.program_id = ?
      ORDER BY b.academic_year DESC, b.block_number ASC;
    `;

    // db.query returns an array: [rows, fields]. We destructure [rows]
    const [rows] = await db.query(query, [programId]);
    return rows;
  }

  /**
   * Insert a new academic block into MySQL
   * @param {Object} blockData - Contains program_id, academic_year, block_number, block_name, start_date, end_date
   */
  static async createBlock(blockData) {
    const { program_id, academic_year, block_number, block_name, start_date, end_date } = blockData;

    const query = `
      INSERT INTO rotation_blocks 
        (program_id, academic_year, block_number, block_name, start_date, end_date)
      VALUES (?, ?, ?, ?, ?, ?);
    `;

    const [result] = await db.query(query, [
      program_id,
      academic_year,
      block_number,
      block_name,
      start_date,
      end_date
    ]);

    // Return the newly created block ID generated by MySQL (AUTO_INCREMENT)
    return {
      block_id: result.insertId,
      ...blockData
    };
  }

  /**
   * Fetch all active clinical rotations for a program
   * @param {number} programId
   */
  static async getRotationsByProgram(programId) {
    const query = `
      SELECT
        r.id AS rotation_id,
        r.program_id,
        r.rotation_code,
        r.rotation_name,
        r.department_name,
        r.department_id,
        r.default_duration_weeks,
        r.is_active
      FROM rotations r
      WHERE r.program_id = ? AND r.is_active = TRUE
      ORDER BY r.rotation_name ASC;
    `;
    const [rows] = await db.query(query, [programId]);
    return rows;
  }

  /**
   * Assign a resident to a rotation block (Full or Split Block)
   * @param {Object} assignmentData
   */
  static async assignResidentToRotation(assignmentData) {
    const {
      resident_id,
      rotation_id,
      rotation_block_id,
      start_date,
      end_date,
      assigned_weeks,
      assignment_type,
      notes
    } = assignmentData;

    const query = `
      INSERT INTO resident_rotation_assignments
        (resident_id, rotation_id, rotation_block_id, start_date, end_date, assigned_weeks, assignment_type, notes)
      VALUES (?, ?, ?, ?, ?, ?, ?, ?);
    `;

    const [result] = await db.query(query, [
      resident_id,
      rotation_id,
      rotation_block_id,
      start_date,
      end_date,
      assigned_weeks || 4.0,
      assignment_type || 'FULL_BLOCK',
      notes || null
    ]);

    return {
      assignment_id: result.insertId,
      ...assignmentData
    };
  }

  /**
   * Get a resident's full rotation schedule across blocks
   * @param {number} residentId
   */
  static async getScheduleByResident(residentId) {
    const query = `
      SELECT
        rra.id AS assignment_id,
        CONCAT(r.first_name, ' ', r.last_name) AS resident_name,
        rb.block_name,
        rot.rotation_name,
        rot.department_name,
        rra.start_date,
        rra.end_date,
        rra.assigned_weeks,
        rra.assignment_type,
        rra.notes
      FROM resident_rotation_assignments rra
      JOIN residents r ON r.id = rra.resident_id
      JOIN rotation_blocks rb ON rb.id = rra.rotation_block_id
      JOIN rotations rot ON rot.id = rra.rotation_id
      WHERE rra.resident_id = ?
      ORDER BY rra.start_date ASC;
    `;
    const [rows] = await db.query(query, [residentId]);
    return rows;
  }
}

module.exports = RotationService;